"""reconstruct_schema

Revision ID: 193d48aeada4
Revises: b7a7c57ca504
Create Date: 2026-04-15 21:59:01.334145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "193d48aeada4"
down_revision: Union[str, Sequence[str], None] = "b7a7c57ca504"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("chat_title", sa.String(length=255), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_check", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_admins_chat_id"), ["chat_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admins_telegram_id"), ["telegram_id"], unique=False
        )

    op.create_table(
        "channel_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("forward_enabled", sa.Boolean(), nullable=False),
        sa.Column("destinations", sa.Text(), nullable=True),
        sa.Column("add_credit", sa.Boolean(), nullable=False),
        sa.Column("credit_text", sa.Text(), nullable=True),
        sa.Column("forward_media", sa.Boolean(), nullable=False),
        sa.Column("forward_text", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("channel_settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_channel_settings_channel_id"), ["channel_id"], unique=True
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "telegram_id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "telegram_id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("channel_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_settings_channel_id"))

    op.drop_table("channel_settings")
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admins_telegram_id"))
        batch_op.drop_index(batch_op.f("ix_admins_chat_id"))

    op.drop_table("admins")
    # ### end Alembic commands ###
